version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - code-repo
    - tekton-catalog-repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'scalable-webapp-kubernetes-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  code-repo:
    service_id: githubconsolidated
    parameters:
      repo_url: 'https://github.com/IBM-Cloud/tutorial-scalable-webapp-kubernetes'
      source_repo_url: 'https://github.com/IBM-Cloud/tutorial-scalable-webapp-kubernetes'
      type: "link"
      has_issues: false
      enable_traceability: false
      ui_pipeline: false
  tekton-catalog-repo:
    service_id: githubconsolidated
    parameters:
      repo_url: "https://github.com/open-toolchain/tekton-catalog"
      source_repo_url: "https://github.com/open-toolchain/tekton-catalog"
      type: "link"
      has_issues: false
      enable_traceability: false
      kind: ['pipeline']
  build:
    service_id: pipeline
    parameters:
      services:
        - code-repo
      name: 'scalable-webapp-kubernetes'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: code-repo
          GIT_REPO_URL: 'https://github.com/IBM-Cloud/tutorial-scalable-webapp-kubernetes'
          GIT_BRANCH: $env.branch
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          INPUT_RESOURCE_PREFIX: '{{form.pipeline.parameters.resource-prefix}}'
          INPUT_RESOURCE_GROUP: '{{form.pipeline.parameters.resource-group}}'
          INPUT_REGION: '{{form.pipeline.parameters.region}}'
        execute: Manual Trigger
form:
  pipeline:
    parameters:
      # allow initialization from environment, i.e from the URL quey parameters
      api-key: '{{apiKey}}'
      resource-prefix: >
        $env.resourcePrefix ?
          '{{resourcePrefix}}' : 'scalable-webapp-kubernetes-{{timestamp}}'
      resource-group: '{{resourceGroup}}'
      region: '{{region}}'
    schema:
      $ref: deploy.json
