apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
    - name: branch
    - name: revision
    - name: apikey
    - name: resource-prefix
    - name: resource-group
    - name: region
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: "" # don't pass the branch, we want to checkout a specific commit
        - name: revision
          value: $(params.revision)
        - name: git-credentials-json-file
          value: .git-credentials.json
      workspaces:
      - name: output
        workspace: pipeline-pvc

    - name: deploy-infrastructure
      taskRef:
        name: local-schematics
      runAfter: [clone-repo]
      params:
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: resource-prefix
          value: $(params.resource-prefix)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc

    - name: get-schematics-outputs
      taskRef:
        name: local-schematics-output
      runAfter: [deploy-infrastructure]
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc

    - name: get-app-code
      taskRef:
        name: local-ibmcloud-cli
      runAfter: [clone-repo]
      params:
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: script
          value: |
            curl -L https://github.com/IBM-Cloud/kubernetes-node-app/archive/refs/heads/master.zip -o app/kube-node-app.zip
            unzip -q app/kube-node-app.zip -d app
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc