apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
    - name: branch
    - name: revision
    - name: apikey
    - name: resource-prefix
    - name: resource-group
    - name: region
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: "" # don't pass the branch, we want to checkout a specific commit
        - name: revision
          value: $(params.revision)
        - name: git-credentials-json-file
          value: .git-credentials.json
      workspaces:
      - name: output
        workspace: pipeline-pvc

    - name: deploy-infrastructure
      taskRef:
        name: local-schematics-create-and-apply
      runAfter: [clone-repo]
      params:
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: resource-prefix
          value: $(params.resource-prefix)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc

    - name: get-schematics-outputs
      taskRef:
        name: local-schematics-output
      runAfter: [deploy-infrastructure]
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc

    - name: get-app-code
      taskRef:
        name: local-ibmcloud-cli
      runAfter: [clone-repo]
      params:
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: script
          value: |
            mkdir -p app
            curl -L https://github.com/IBM-Cloud/kubernetes-node-app/archive/refs/heads/master.zip -o app/kube-node-app.zip
            unzip -q app/kube-node-app.zip -d app
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc

    - name: build-image
      taskRef:
        name: icr-containerize
      runAfter: [get-schematics-outputs, get-app-code]
      params:
        - name: registry-region
          value: $(params.region)
        - name: registry-namespace
          value: $(tasks.get-schematics-outputs.results.registry-namespace)
        - name: image-name
          value: "$(params.resource-prefix)-image"
        - name: resource-group
          value: $(params.resource-group)
        - name: path-to-context
          value: app/kubernetes-node-app-master
        - name: path-to-dockerfile
          value: app/kubernetes-node-app-master
        - name: additional-tags
          value: "v1.0.0"
      workspaces:
      - name: source
        workspace: pipeline-pvc

    - name: deploy-app
      taskRef:
        name: local-ibmcloud-cli
      runAfter: [build-image]
      params:
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: script
          value: |
            export MYCLUSTER=$(tasks.get-schematics-outputs.results.cluster-name)
            export KUBERNETES_NAMESPACE=$(tasks.get-schematics-outputs.results.kubernetes-namespace)
            export MYPROJECT=$(params.resource-prefix)-app

            ibmcloud ks cluster config --cluster $MYCLUSTER
            export INGRESS_SUBDOMAIN=$(ibmcloud ks cluster get --cluster $MYCLUSTER --output json | jq -r '.ingress.hostname')
            export INGRESS_SECRET_NAME=$(ibmcloud ks cluster get --cluster $MYCLUSTER --output json | jq -r '.ingress.secretName')

            if [[ "$KUBERNETES_NAMESPACE" != "default" ]]; then
              # secret to access container registry images
              kubectl get secret all-icr-io -n default -o yaml | sed "s/default/$KUBERNETES_NAMESPACE/g" | kubectl create -n $KUBERNETES_NAMESPACE -f - || true
              kubectl patch -n $KUBERNETES_NAMESPACE serviceaccount/default -p '{"imagePullSecrets":[{"name": "all-icr-io"}]}' || true

              # secret to secure ingress https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-migrate-1
              INGRESS_SECRET_CRN=$(ibmcloud ks ingress secret get -c $MYCLUSTER --name $INGRESS_SECRET_NAME --namespace default --output json | jq -r .crn)
              ibmcloud ks ingress secret create --cluster $MYCLUSTER --cert-crn $INGRESS_SECRET_CRN --name $INGRESS_SECRET_NAME --namespace $KUBERNETES_NAMESPACE || true
            fi

            cd app/kubernetes-node-app-master

            # deploy the service
            cd chart/kubernetesnodeapp

            # install helm 3
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            helm version --client
            helm upgrade $MYPROJECT . --install --namespace $KUBERNETES_NAMESPACE --set image.repository=$(tasks.build-image.results.image-repository) || true

            # deploy an ingress
            cd ../../
            ./ingress.sh ibmdomain_https
            kubectl apply -f ingress-ibmdomain.yaml

            sleep 20

            echo "The application should be running at https://$MYPROJECT.$INGRESS_SUBDOMAIN/"
            curl -v https://$MYPROJECT.$INGRESS_SUBDOMAIN/
      workspaces:
      - name: artifacts
        workspace: pipeline-pvc
